apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authentication-microservice
  template:
    metadata:
      labels:
        app: authentication-microservice
    spec:
      containers:
        - name: authentication-microservice
          image: 329599629502.dkr.ecr.eu-west-3.amazonaws.com/authentication-microservice:latest
          ports:
            - containerPort: 8081