apiVersion: v1
kind: Service
metadata:
  name: authentication-microservice
spec:
  selector:
    app: authentication-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer