apiVersion: v1
kind: Service
metadata:
  name: authentification-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  
    alb.ingress.kubernetes.io/scheme: internet-facing         
    alb.ingress.kubernetes.io/target-type: ip                
spec:
  selector:
    app: authentification
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 8081   
  type: LoadBalancer
